//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] e_0x200 {
            get {
                object obj = ResourceManager.GetObject("e_0x200", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] n_0x200 {
            get {
                object obj = ResourceManager.GetObject("n_0x200", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Elements xmlns=&quot;ConsoleForms&quot;&gt;
        ///  &lt;!-- Networking context --&gt;
        ///  &lt;InputTextBox id=&quot;NetConnect&quot;
        ///                padding_left=&quot;2&quot;
        ///                padding_right=&quot;2&quot;
        ///                padding_top=&quot;1&quot;
        ///                padding_bottom=&quot;1&quot;&gt;
        ///    &lt;Fields&gt;
        ///      &lt;Field input_type=&quot;decimal&quot; max_length=&quot;15&quot;&gt;Server IP:&lt;/Field&gt;
        ///      &lt;Field default=&quot;80&quot; input_type=&quot;integer&quot; max_length=&quot;5&quot;&gt;Port:&lt;/Field&gt;
        ///    &lt;/Fields&gt;
        ///    &lt;Text&gt;Server connection configuration&lt;/Text&gt;
        ///  &lt;/Input [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Networking {
            get {
                return ResourceManager.GetString("Networking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Elements xmlns=&quot;ConsoleForms&quot;&gt;
        ///  &lt;DialogBox id=&quot;Success&quot;
        ///    padding_left=&quot;2&quot;
        ///    padding_right=&quot;2&quot;
        ///    padding_top=&quot;1&quot;
        ///    padding_bottom=&quot;1&quot;&gt;
        ///    &lt;Options&gt;
        ///      &lt;Option&gt;Quit&lt;/Option&gt;
        ///    &lt;/Options&gt;
        ///    &lt;Text&gt;Login succeeded!&lt;/Text&gt;
        ///  &lt;/DialogBox&gt;
        ///&lt;/Elements&gt;.
        /// </summary>
        internal static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Elements xmlns=&quot;ConsoleForms&quot;&gt;
        ///  
        ///  &lt;!-- Welcome screen --&gt;
        ///  &lt;DialogBox id=&quot;WelcomeScreen&quot;
        ///             padding_left=&quot;2&quot;
        ///             padding_right=&quot;2&quot;
        ///             padding_top=&quot;1&quot;
        ///             padding_bottom=&quot;1&quot;
        ///             width=&quot;42&quot;&gt;
        ///    &lt;Options&gt;
        ///      &lt;Option event=&quot;Setup:Login&quot; close=&quot;true&quot;&gt;Login&lt;/Option&gt;
        ///      &lt;Option event=&quot;Setup:Register&quot; close=&quot;true&quot;&gt;Register&lt;/Option&gt;
        ///    &lt;/Options&gt;
        ///    &lt;Text&gt;Welcome to the Tofvesson banking system! To conti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
    }
}
