//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;Resources xmlns=&quot;Client.ConsoleForms.Graphics&quot;&gt;
        ///  &lt;DialogView id=&quot;EmptyFieldError&quot;
        ///    padding_left=&quot;2&quot;
        ///    padding_right=&quot;2&quot;
        ///    padding_top=&quot;1&quot;
        ///    padding_bottom=&quot;1&quot;&gt;
        ///    &lt;Options&gt;
        ///      &lt;Option&gt;@string/GENERIC_accept&lt;/Option&gt;
        ///    &lt;/Options&gt;
        ///    &lt;Text&gt;@string/ERR_empty&lt;/Text&gt;
        ///  &lt;/DialogView&gt;
        ///
        ///  &lt;DialogView id=&quot;ConnectionError&quot;
        ///    padding_left=&quot;2&quot;
        ///    padding_right=&quot;2&quot;
        ///    padding_top=&quot;1&quot;
        ///    padding_bottom=&quot;1&quot;
        ///             border=&quot;4&quot;&gt;
        ///    &lt;Opt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] e_0x100 {
            get {
                object obj = ResourceManager.GetObject("e_0x100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] e_0x200 {
            get {
                object obj = ResourceManager.GetObject("e_0x200", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;Elements xmlns=&quot;Client.ConsoleForms.Graphics&quot;&gt;
        ///
        ///	&lt;!-- First dialog that welcomes new user --&gt;
        ///  &lt;DialogView id=&quot;welcome&quot;
        ///    padding_left=&quot;2&quot;
        ///    padding_right=&quot;2&quot;
        ///    padding_top=&quot;1&quot;
        ///    padding_bottom=&quot;1&quot;&gt;
        ///    &lt;Options&gt;
        ///      &lt;Option&gt;@string/WS_accept&lt;/Option&gt;
        ///      &lt;Option&gt;@string/WS_dismiss&lt;/Option&gt;
        ///    &lt;/Options&gt;
        ///    &lt;Text&gt;@string/WS_welcome&lt;/Text&gt;
        ///  &lt;/DialogView&gt;
        ///
        ///  &lt;!-- First intro dialog --&gt;
        ///  &lt;DialogView id=&quot;describe1&quot;
        ///    padding_left=&quot;2&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] n_0x100 {
            get {
                object obj = ResourceManager.GetObject("n_0x100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] n_0x200 {
            get {
                object obj = ResourceManager.GetObject("n_0x200", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Elements xmlns=&quot;Client.ConsoleForms.Graphics&quot;&gt;
        ///  &lt;!-- Networking context --&gt;
        ///  &lt;InputView id=&quot;NetConnect&quot;
        ///                padding_left=&quot;2&quot;
        ///                padding_right=&quot;2&quot;
        ///                padding_top=&quot;1&quot;
        ///                padding_bottom=&quot;1&quot;&gt;
        ///    &lt;Fields&gt;
        ///      &lt;Field input_type=&quot;decimal&quot; max_length=&quot;15&quot;&gt;@string/NC_ip&lt;/Field&gt;
        ///      &lt;Field default=&quot;80&quot; input_type=&quot;integer&quot; max_length=&quot;5&quot;&gt;@string/NC_port&lt;/Field&gt;
        ///    &lt;/Fields&gt;
        ///    &lt;Text&gt;@string/NC_head&lt;/Text&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Networking {
            get {
                return ResourceManager.GetString("Networking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Elements xmlns=&quot;Client.ConsoleForms.Graphics&quot;&gt;
        ///  &lt;DialogView id=&quot;Success&quot;
        ///    padding_left=&quot;2&quot;
        ///    padding_right=&quot;2&quot;
        ///    padding_top=&quot;1&quot;
        ///    padding_bottom=&quot;1&quot;&gt;
        ///    &lt;Options&gt;
        ///      &lt;Option&gt;Quit&lt;/Option&gt;
        ///    &lt;/Options&gt;
        ///    &lt;Text&gt;Login succeeded!&lt;/Text&gt;
        ///  &lt;/DialogView&gt;
        ///  
        ///  &lt;TextView id=&quot;balance&quot;
        ///    padding_left=&quot;2&quot;
        ///    padding_right=&quot;2&quot;
        ///    padding_top=&quot;1&quot;
        ///    padding_bottom=&quot;1&quot;&gt;
        ///    &lt;Text&gt;@string/SE_bal&lt;/Text&gt;
        ///  &lt;/TextView&gt;
        ///
        ///  &lt;TextView id=&quot;acco [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Elements xmlns=&quot;Client.ConsoleForms.Graphics&quot;&gt;
        ///  
        ///  &lt;!-- Welcome screen --&gt;
        ///  &lt;DialogView id=&quot;WelcomeScreen&quot;
        ///             padding_left=&quot;2&quot;
        ///             padding_right=&quot;2&quot;
        ///             padding_top=&quot;1&quot;
        ///             padding_bottom=&quot;1&quot;
        ///             width=&quot;42&quot;&gt;
        ///    &lt;Options&gt;
        ///      &lt;Option event=&quot;Setup:Login&quot; close=&quot;true&quot;&gt;@string/SU_login_label&lt;/Option&gt;
        ///      &lt;Option event=&quot;Setup:Register&quot; close=&quot;true&quot;&gt;@string/SU_reg_label&lt;/Option&gt;
        ///    &lt;/Options&gt;
        ///    &lt;Text&gt;@st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;Strings label=&quot;English&quot;&gt;
        ///	&lt;Entry name=&quot;WS_welcome&quot;&gt;Hello and welcome to the ConsoleForms bank project!
        ///If you are unfamiliar with ConsoleForms and would like to
        ///familiarize yourself with it, we are offering a beginner&apos;s
        ///guide to the format! Note: This dialog will never be show again.
        ///Would you like to be shown the features of ConsoleForms
        ///before proceeding?&lt;/Entry&gt;
        ///	&lt;Entry name=&quot;WS_dismiss&quot;&gt;No thank you&lt;/Entry&gt;
        ///	&lt;Entry name=&quot;WS_accept&quot;&gt;Teach me&lt;/Entry&gt;
        ///	&lt;E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string strings_lang_en_GB {
            get {
                return ResourceManager.GetString("strings_lang_en_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;Strings label=&quot;English&quot;&gt;
        ///	&lt;Entry name=&quot;WS_welcome&quot;&gt;Hello and welcome to the ConsoleForms bank project!
        ///If you are unfamiliar with ConsoleForms and would like to
        ///familiarize yourself with it, we are offering a beginner&apos;s
        ///guide to the format! Note: This dialog will never be show again.
        ///Would you like to be shown the features of ConsoleForms
        ///before proceeding?&lt;/Entry&gt;
        ///	&lt;Entry name=&quot;WS_dismiss&quot;&gt;No thank you&lt;/Entry&gt;
        ///	&lt;Entry name=&quot;WS_accept&quot;&gt;Teach me&lt;/Entry&gt;
        ///	&lt;E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string strings_lang_en_US {
            get {
                return ResourceManager.GetString("strings_lang_en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;Strings label=&quot;Svenska&quot;&gt;
        ///	&lt;Entry name=&quot;WS_welcome&quot;&gt;Hej och välkommen till ConsoleForms bankprojektet!
        ///Om du är ovan vid ConsoleForms-gränssnittet och vill
        ///vänja dig vid dess funktioner, så finns det en guide
        ///till gränssnittet!
        ///Notera att denna dialog aldrig kommer att visas igen.
        ///Vill du gå igenom en introduktion till gränssnittet?&lt;/Entry&gt;
        ///	&lt;Entry name=&quot;WS_dismiss&quot;&gt;Nej tack&lt;/Entry&gt;
        ///	&lt;Entry name=&quot;WS_accept&quot;&gt;Ja tack&lt;/Entry&gt;
        ///	&lt;Entry name=&quot;WS_continue&quot;&gt;Nästa&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string strings_lang_sv_SE {
            get {
                return ResourceManager.GetString("strings_lang_sv_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;Strings&gt;
        ///	&lt;Lang priority=&quot;0&quot;&gt;sv_SE&lt;/Lang&gt;
        ///	&lt;Lang priority=&quot;1&quot;&gt;en_US&lt;/Lang&gt;
        ///	&lt;Lang priority=&quot;2&quot;&gt;en_GB&lt;/Lang&gt;
        ///&lt;/Strings&gt;.
        /// </summary>
        internal static string strings_meta {
            get {
                return ResourceManager.GetString("strings_meta", resourceCulture);
            }
        }
    }
}
